name: Daily Market Scraper

on:
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install gspread google-auth gspread-dataframe yagmail pandas selenium beautifulsoup4

    - name: Set up Chrome and ChromeDriver
      uses: nanasess/setup-chromedriver@v1
      with:
        chrome-version: latest

    - name: Run Arenakit Pipeline
      env:
        EMAIL_APP_PASSWORD: ${{ secrets.EMAIL_APP_PASSWORD }}
        GOOGLE_KEY_JSON: ${{ secrets.GOOGLE_KEY_JSON }}
      run: |
        echo "=== Starting Arenakit Pipeline ==="
        python "Football TShirts Scrapping/arena.py"
        echo "=== Arenakit Pipeline Finished ==="

    - name: Run Curva Pipeline
      env:
        EMAIL_APP_PASSWORD: ${{ secrets.EMAIL_APP_PASSWORD }}
        GOOGLE_KEY_JSON: ${{ secrets.GOOGLE_KEY_JSON }}
      run: |
        echo "=== Starting Curva Pipeline ==="
        python "Football TShirts Scrapping/curva.py"
        echo "=== Curva Pipeline Finished ==="
