name: Daily Market Scraper

on:
  schedule:
    - cron: "0 7 * * *"   # كل يوم الساعة 7 صباحًا
  workflow_dispatch:       # لتشغيل يدوي

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-driver  # ضروري للـ Curva
        pip install gspread google-auth gspread-dataframe beautifulsoup4 yagmail pandas selenium

    - name: Run Arenakit Pipeline
      env:
        EMAIL_APP_PASSWORD: ${{ secrets.EMAIL_APP_PASSWORD }}
        GOOGLE_KEY_JSON: ${{ secrets.GOOGLE_KEY_JSON }}
      run: |
        echo "=== Starting Arenakit Pipeline ==="
        python "Football TShirts Scrapping/arena.py"
        echo "=== Arenakit Pipeline Finished ==="

    - name: Run Curva Pipeline
      env:
        EMAIL_APP_PASSWORD: ${{ secrets.EMAIL_APP_PASSWORD }}
        GOOGLE_KEY_JSON: ${{ secrets.GOOGLE_KEY_JSON }}
      run: |
        echo "=== Starting Curva Pipeline ==="
        python "Football TShirts Scrapping/curva.py"
        echo "=== Curva Pipeline Finished ==="
